import { ROLES } from "./constants";

export const PERMISSIONS = {
  MANAGE_STAFF: "manage_staff",
  VIEW_DASHBOARD: "view_dashboard",
  VIEW_PATIENTS: "view_patients",
  MANAGE_PATIENTS: "manage_patients",
  MANAGE_APPOINTMENTS: "manage_appointments",
  VIEW_BILLING: "view_billing",
  MANAGE_BILLING: "manage_billing",
  COMMUNICATE: "communicate",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.COMMUNICATE,
  ],
  [ROLES.PROVIDER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_APPOINTMENTS,
    PERMISSIONS.COMMUNICATE,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING,
  ],
  [ROLES.NURSE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_APPOINTMENTS,
    PERMISSIONS.COMMUNICATE,
  ],
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.MANAGE_APPOINTMENTS,
  ],
  [ROLES.PHARMACIST]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PATIENTS,
  ],
  [ROLES.PATIENT]: [
    PERMISSIONS.VIEW_BILLING,
  ],
};

export const hasPermission = (role, permission) => {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[String(role).toLowerCase()] || [];
  return permissions.includes(permission);
};